---
title: "dilution plots"
output: html_document
date: "2023-09-27"
---

#Setup

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library("readxl")

all_data <- read_excel("ree_data_r.xlsx", 1)
cement_data <- read_excel("ree_data_r.xlsx", 2)
dilute_data <- read_excel("diluted data.xlsx", 5)
colnames(dilute_data) <- c("Sample", "Na_ppm", "Mg_ppm", "K_ppm", "Ca_ppm", "V_ppm", "Cr_ppm", "Fe_ppm", "Mn_ppm", "Cu_pm", "Zn_pm", "Rb_ppm", "Sr_ppm", "Y_ppm", "Mo_ppm", "In_ppm", "Ba_ppm", "La_ppm", "Ce_ppm", "Pr_ppm", "Nd_ppm", "Sm_ppm", "Eu_pm", "Gd_ppm", "Dy_ppm", "Ho_pm", "Er_ppm", "Tm_ppm", "Yb_ppm", "Lu_ppm", "Pb_ppm", "U_ppm")
```

#Data Tables

```{r data wrangle ree only}
ree_data <- all_data %>%
  select("Sample", "Y_ppm", "La_ppm", "Ce_ppm", "Pr_ppm", "Nd_ppm", "Sm_ppm", "Eu_ppm",  "Gd_ppm","Dy_ppm", "Ho_ppm", "Er_ppm", "Tm_ppm", "Yb_ppm", "Lu_ppm") #filter out non REY elements\
ree_data <- data.frame(t(ree_data[-1])) #transpose and remove first row containing sample names
colnames(ree_data) <- all_data$Sample #rename column names with sample names
ree_data <- tibble::rownames_to_column(ree_data, "element") %>%
  mutate(element = fct_inorder(element)) #order elements

ree_dilute <- dilute_data %>%
  select("Sample", "Y_ppm", "La_ppm", "Ce_ppm", "Pr_ppm", "Nd_ppm", "Sm_ppm", "Eu_ppm",  "Gd_ppm","Dy_ppm", "Ho_ppm", "Er_ppm", "Tm_ppm", "Yb_ppm", "Lu_ppm") #filter out non REY elements\
ree_dilute <- data.frame(t(ree_dilute[-1])) #transpose and remove first row containing sample names
colnames(ree_dilute) <- dilute_data$Sample #rename column names with sample names
ree_dilute <- tibble::rownames_to_column(ree_dilute, "element") %>%
  mutate(element = fct_inorder(element)) #order elements
```

```{r paas normalized pourmand et al 2012}
attach(all_data)
normalize <- all_data %>%
  select("Sample", "La_ppm", "Ce_ppm", "Pr_ppm", "Nd_ppm", "Sm_ppm", "Eu_ppm",  "Gd_ppm","Dy_ppm", "Y_ppm",  "Ho_ppm", "Er_ppm", "Tm_ppm", "Yb_ppm", "Lu_ppm") %>% #filter out non REY elements
  mutate(Y_normal = Y_ppm/27.31, La_normal = La_ppm/44.56, Ce_normal = Ce_ppm/88.25, Pr_normal = Pr_ppm/10.15, Nd_normal = Nd_ppm/37.32, Sm_normal = Sm_ppm/6.884, Eu_normal = Eu_ppm/1.215, Gd_normal = Gd_ppm/6.043, Dy_normal = Dy_ppm/5.325, Ho_normal = Ho_ppm/1.052, Er_normal = Er_ppm/3.075, Tm_normal = Tm_ppm/0.4510, Yb_normal = Yb_ppm/3.012, Lu_normal = Lu_ppm/0.4386) %>% #normalize values using PAAS data from Pourmand et al. 2012
    select("Sample", "La_normal", "Ce_normal", "Pr_normal", "Nd_normal", "Sm_normal", "Eu_normal",  "Gd_normal","Dy_normal", "Y_normal", "Ho_normal", "Er_normal", "Tm_normal", "Yb_normal", "Lu_normal") %>% #filter out non normalized values
  left_join(cement_data, by = c("Sample" = "Sample")) #attach cement to each observation

normal <- data.frame(t(normalize[2:15]))#transpose and remove first row containing sample names and cement row
colnames(normal) <- all_data$Sample #rename column names with sample names
normal <- tibble::rownames_to_column(normal, "element") %>%
  mutate(element = fct_inorder(element)) %>% #order elements
  pivot_longer(-element, names_to = "Sample", values_to = "Value") %>% #pivot data to have each element value as observation
  left_join(cement_data, by = c("Sample" = "Sample")) #attach cement to each observation
```

```{r anomaly calculations}
rawAnomaly <- normalize %>%
  mutate(Ce_anomaly = Ce_normal/(Pr_normal^2/Nd_normal),
    Y_Ho_ratio = Y_normal/Ho_normal) %>%
  select(Sample, Cement, Ce_anomaly, Y_Ho_ratio)
rawAnomaly

anomaly <- normalize %>%
  mutate(
    Ce_anomaly = Ce_normal/(Pr_normal^2/Nd_normal),
    Y_Ho_ratio = Y_normal/Ho_normal,
    Eu_anomaly = (2*Eu_normal)/(Sm_normal + Gd_normal),
    BSI = (2*(Sm_normal + Gd_normal + Dy_normal)/3)/((La_normal +Pr_normal + Nd_normal)/3+(Ho_normal + Er_normal +Tm_normal +Yb_normal +Lu_normal)/5)) %>%
  group_by(Cement) %>%
  summarise(
    Ce_mean = mean(Ce_anomaly),
    Ce_sd = sd(Ce_anomaly),
    Ce_max = max(Ce_anomaly),
    Ce_min = min(Ce_anomaly),
    YH_mean = mean(Y_Ho_ratio),
    YH_sd = sd(Y_Ho_ratio),
    YH_max = max(Y_Ho_ratio),
    YH_min = min(Y_Ho_ratio),
    Eu_mean = mean(Eu_anomaly),
    Eu_sd = sd(Eu_anomaly),
    Eu_max = max(Eu_anomaly),
    Eu_min = min(Eu_anomaly),
    BSI_mean = mean(BSI),
    BSI_sd = sd(BSI),
    BSI_max = max(BSI),
    BSI_min = min(BSI)
  )
anomaly
```