---
title: "ree stats"
author: "Clara Wong"
date: "2023-05-02"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(tidyverse)
library(readxl)
```

## Data Import
```{r}
all_data <- read_excel("ree_data_r.xlsx", 1)
cement_data <- read_excel("ree_data_r.xlsx", 2)
```

## Data Wrangle
```{r paas normalized pourmand et al 2012}
attach(all_data)
normalize <- all_data %>%
  left_join(cement_data, by = c("Sample" = "Sample")) %>% #attach cement to each observation
#  filter(Cement != "Manganese") %>% #removes manganese samples
  mutate(Y_normal = Y_ppm/27.31, La_normal = La_ppm/44.56, Ce_normal = Ce_ppm/88.25, Pr_normal = Pr_ppm/10.15, Nd_normal = Nd_ppm/37.32, Sm_normal = Sm_ppm/6.884, Eu_normal = Eu_ppm/1.215, Gd_normal = Gd_ppm/6.043, Dy_normal = Dy_ppm/5.325, Ho_normal = Ho_ppm/1.052, Er_normal = Er_ppm/3.075, Tm_normal = Tm_ppm/0.4510, Yb_normal = Yb_ppm/3.012, Lu_normal = Lu_ppm/0.4386) %>% #normalize values using PAAS data from Pourmand et al. 2012
    dplyr::select(Sample, Cement, La_normal, Ce_normal, Pr_normal, Nd_normal, Sm_normal, Eu_normal, Gd_normal,Dy_normal, Y_normal, Ho_normal, Er_normal, Tm_normal, Yb_normal)#filter out non normalized values and Lu
```

```{r Ce anomaly and Y/Ho}
rawAnomaly <- normalize %>%
  mutate(Ce_anomaly = Ce_normal/(Pr_normal^2/Nd_normal),
    Y_Ho_ratio = Y_normal/Ho_normal) %>%
  select(Sample, Cement, Ce_anomaly, Y_Ho_ratio)
rawAnomaly
```

## Normality
```{r kolmogorov-smirnov normalized conc}
ks_result <- normalize %>%
  mutate(Eu_normal = ifelse(Eu_normal > 4, NA, Eu_normal)) %>%
  group_by(Cement) %>%
  summarize(
    ks_La <- ks.test(La_normal, "pnorm")$p.value,
    ks_Ce <- ks.test(Ce_normal, "pnorm")$p.value,
    ks_Pr <- ks.test(Pr_normal, "pnorm")$p.value,
    ks_Nd <- ks.test(Nd_normal, "pnorm")$p.value,
    ks_Sm <- ks.test(Sm_normal, "pnorm")$p.value,
    ks_Eu <- ks.test(Eu_normal, "pnorm")$p.value,
    ks_Gd <- ks.test(Gd_normal, "pnorm")$p.value,
    ks_Dy <- ks.test(Dy_normal, "pnorm")$p.value,
    ks_Y <- ks.test(Y_normal, "pnorm")$p.value,
    ks_Ho <- ks.test(Ho_normal, "pnorm")$p.value,
    ks_Er <- ks.test(Er_normal, "pnorm")$p.value,
    ks_Tm <- ks.test(Tm_normal, "pnorm")$p.value,
    ks_Yb <- ks.test(Yb_normal, "pnorm")$p.value
  )
colnames(ks_result) <- c("Cement", "La", "Ce", "Pr", "Nd", "Sm", "Eu", "Gd", "Dy", "Y", "Ho", "Er", "Tm", "Yb")
ks_result
```

```{r shapiro-wilk normalized conc}
sw_result <- normalize %>%
  group_by(Cement) %>%
  mutate(Cement = case_when(
    str_detect(Cement, "Micrite") == TRUE ~ "Micrite",
    str_detect(Cement, "Microbial") == TRUE ~ "Microbial",
    TRUE ~ as.character(Cement)
   )) %>%
  filter(Cement != "Manganese") %>%
  summarize(
    sw_La <- shapiro.test(La_normal)$p.value,
    sw_Ce <- shapiro.test(Ce_normal)$p.value,
    sw_Pr <- shapiro.test(Pr_normal)$p.value,
    sw_Nd <- shapiro.test(Nd_normal)$p.value,
    sw_Sm <- shapiro.test(Sm_normal)$p.value,
    sw_Eu <- shapiro.test(Eu_normal)$p.value,
    sw_Gd <- shapiro.test(Gd_normal)$p.value,
    sw_Dy <- shapiro.test(Dy_normal)$p.value,
    sw_Y <- shapiro.test(Y_normal)$p.value,
    sw_Ho <- shapiro.test(Ho_normal)$p.value,
    sw_Er <- shapiro.test(Er_normal)$p.value,
    sw_Tm <- shapiro.test(Tm_normal)$p.value,
    sw_Yb <- shapiro.test(Yb_normal)$p.value
  )
colnames(sw_result) <- c("Cement", "La", "Ce", "Pr", "Nd", "Sm", "Eu", "Gd", "Dy", "Y", "Ho", "Er", "Tm", "Yb")
sw_result
```

```{r shapiro-wilk Ce anomaly}
sw_Ce <- rawAnomaly %>%
  group_by(Cement) %>%
  mutate(Cement = case_when(
    str_detect(Cement, "Micrite") == TRUE ~ "Micrite",
    str_detect(Cement, "Microbial") == TRUE ~ "Microbial",
    TRUE ~ as.character(Cement)
   )) %>%
  filter(Cement != "Manganese") %>%
  summarise(
    shapiro.test(Ce_anomaly)$p.value
  )
```

```{r Ce wilcoxon}
micriteMicro <- rawAnomaly %>%
  filter(Cement == case_when(
    str_detect(Cement, "Micrite") == TRUE ~ "Micrite",
    str_detect(Cement, "Microbial") == TRUE ~ "Microbial"
  ))

micriteMicro$Cement <- factor(micriteMicro$Cement, levels = c("Micrite", "Microbial"))

wilcox.test(micriteMicro$Ce_anomaly ~ micriteMicro$Cement)
```