---
title: "ree stats"
output: html_document
date: "2023-04-12"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(readxl)
library(vegan)
```

## Data Import
```{r}
all_data <- read_excel("ree_data_r.xlsx", 1)
cement_data <- read_excel("ree_data_r.xlsx", 2)
```

## Data Wrangle
```{r paas normalized pourmand et al 2012}
attach(all_data)
normalize <- all_data %>%
  left_join(cement_data, by = c("Sample" = "Sample")) %>% #attach cement to each observation
  filter(Cement != "Manganese") %>% #removes manganese samples
  mutate(Y_normal = Y_ppm/27.31, La_normal = La_ppm/44.56, Ce_normal = Ce_ppm/88.25, Pr_normal = Pr_ppm/10.15, Nd_normal = Nd_ppm/37.32, Sm_normal = Sm_ppm/6.884, Eu_normal = Eu_ppm/1.215, Gd_normal = Gd_ppm/6.043, Dy_normal = Dy_ppm/5.325, Ho_normal = Ho_ppm/1.052, Er_normal = Er_ppm/3.075, Tm_normal = Tm_ppm/0.4510, Yb_normal = Yb_ppm/3.012, Lu_normal = Lu_ppm/0.4386) %>% #normalize values using PAAS data from Pourmand et al. 2012
    select("Sample", "Cement", "La_normal", "Ce_normal", "Pr_normal", "Nd_normal", "Sm_normal", "Eu_normal",  "Gd_normal","Dy_normal", "Y_normal", "Ho_normal", "Er_normal", "Tm_normal", "Yb_normal")#filter out non normalized values and Lu
normalize$Cement = factor(normalize$Cement, levels = c("Micrite (SSF)", "Micrite", "Laminar Calcrete", "Laminar Microbial", "Microbial (SSF)", "Microbial"))
```

## Stats
``` {r run nmds}
ree_matrix <- as.matrix(normalize[,3:ncol(normalize)])
set.seed(123)
nmds = metaMDS(ree_matrix, distance = "bray")
nmds
```

```{r prep data for plotting}
data_scores = as.data.frame(scores(nmds)$sites)
data_scores$Sample = normalize$Sample
data_scores$Cement = normalize$Cement

species_scores <- as.data.frame(scores(nmds, "species"))
species_scores$species <- rownames(species_scores)

hull <- data_scores %>%
  group_by(Cement) %>%
  slice(chull(NMDS1, NMDS2))
```


## Plot
```{r}
nmds_plot <- ggplot(data_scores, aes(x = NMDS1, y = NMDS2)) +
  geom_point(aes(color = forcats::fct_rev(Cement))) +
  geom_polygon(data = hull, alpha = .6, aes(fill = forcats::fct_rev(Cement))) +
  geom_text(data = species_scores, color = "black", aes(x = NMDS1, y = NMDS2, label = species)) +
  annotate(geom = "text", x = 1, y = -.15, label = nmds$stress, color = "black") +
  scale_color_brewer(palette = "Set1", name = "Texture") +
  scale_fill_brewer(palette = "Set1", name = "Texture") +
  theme(
    panel.background = element_rect(fill = "#C3C3C3"),
    panel.grid = element_blank(),
    legend.key = element_rect(fill = "#C3C3C3")
  )
nmds_plot
```