---
title: "Rerun"
author: "Clara Wong"
date: "2024-01-29"
output: html_document
editor_options: 
  chunk_output_type: console
---

## Import and Setup

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse) #for working with data
library(readxl) #for importing excel sheets
```

```{r}
orig_data <- read_xlsx("ree_data_r.xlsx", 1) #data from single leach
rerun_data <- read_xlsx("jan2024 data.xlsx",4) #data for sequential leach
dil_data <- read_xlsx("jan2024 data DILUTED.xlsx",4) #data for diluted seq leach rerun
cement_data <- read_excel("ree_data_r.xlsx", 2) #cement type data for all samples
```

## Data Wrangle

```{r reorganize data tables}
#rename columns to just element
orig_data <- orig_data %>%
  rename(Sample = 1, Na = 2, Mg  = 3, K = 4, Ca = 5, V = 6, Cr = 7, Fe = 8, Mn = 9, Cu = 10, Zn = 11, Rb = 12, Sr = 13, Y = 14, Mo = 15, Ba = 16, La = 17, Ce = 18, Pr = 19, Nd = 20, Sm = 21, Eu = 22, Gd = 23, Dy = 24, Ho = 25, Er = 26, Tm = 27, Yb = 28, Lu = 29, Pb = 30, U = 31)

rerun_data <- rerun_data[-1,] %>% #removes first line with no values
  rename(Sample = 1, Na = 2, Mg  = 3, K = 4, Ca = 5, V = 6, Cr = 7, Fe = 8, Mn = 9, Cu = 10, Zn = 11, Rb = 12, Sr = 13, Y = 14, Mo = 15, Ba = 16, La = 17, Ce = 18, Pr = 19, Nd = 20, Sm = 21, Eu = 22, Gd = 23, Dy = 24, Ho = 25, Er = 26, Tm = 27, Yb = 28, Lu = 29, Pb = 30, U = 31)

dil_data <- dil_data[-1,] %>% #removes first line with no values
  rename(Sample = 1, Na = 2, Mg  = 3, K = 4, Ca = 5, V = 6, Cr = 7, Fe = 8, Mn = 9, Cu = 10, Zn = 11, Rb = 12, Sr = 13, Y = 14, Mo = 15, Ba = 16, La = 17, Ce = 18, Pr = 19, Nd = 20, Sm = 21, Eu = 22, Gd = 23, Dy = 24, Ho = 25, Er = 26, Tm = 27, Yb = 28, Lu = 29, Pb = 30, U = 31)

all_rerun <- bind_rows(rerun_data, dil_data) %>% #combine both seq leach datasets
  mutate_at(2:31, as.numeric) #convert data from character to numeric
```

## Normalization

```{r orig paas normalized pourmand et al 2012}
attach(orig_data)
orig_normalize <- orig_data %>%
  select("Sample", "La", "Ce", "Pr", "Nd", "Sm", "Eu", "Gd", "Dy", "Y", "Ho", "Er", "Tm", "Yb", "Lu") %>% #filter out non REY elements
  mutate(La = La/44.56, Ce = Ce/88.25, Pr = Pr/10.15, Nd = Nd/37.32, Sm = Sm/6.884, Eu = Eu/1.215, Gd = Gd/6.043, Dy = Dy/5.325, Y = Y/27.31, Ho = Ho/1.052, Er = Er/3.075, Tm = Tm/0.4510, Yb = Yb/3.012, Lu = Lu/0.4386) %>% #normalize values using PAAS data from Pourmand et al. 2012
    select("Sample", "La", "Ce", "Pr", "Nd", "Sm", "Eu", "Gd", "Dy", "Y", "Ho", "Er", "Tm", "Yb", "Lu") %>% #filter out non normalized values
  left_join(cement_data, by = c("Sample" = "Sample")) %>% #attach cement to each observation 
mutate(Lu = NA) #Lu was not detected, change 0 to NA


orig_normal <- data.frame(t(orig_normalize[2:15]))#transpose and remove first row containing sample names and cement row
colnames(orig_normal) <- orig_data$Sample #rename column names with sample names
orig_normal <- tibble::rownames_to_column(orig_normal, "element") %>%
  mutate(element = fct_inorder(element)) %>% #order elements
  pivot_longer(-element, names_to = "Sample", values_to = "Value") %>% #pivot data to have each element value as observation
  left_join(cement_data, by = c("Sample" = "Sample")) #attach cement to each observation
```

```{r rerun paas normalized pourmand et al 2012}
attach(all_rerun)
normalize <- all_rerun %>%
  select("Sample", "La", "Ce", "Pr", "Nd", "Sm", "Eu", "Gd", "Dy", "Y", "Ho", "Er", "Tm", "Yb", "Lu") %>% #filter out non REY elements
  mutate(La = La/44.56, Ce = Ce/88.25, Pr = Pr/10.15, Nd = Nd/37.32, Sm = Sm/6.884, Eu = Eu/1.215, Gd = Gd/6.043, Dy = Dy/5.325, Y = Y/27.31, Ho = Ho/1.052, Er = Er/3.075, Tm = Tm/0.4510, Yb = Yb/3.012, Lu = Lu/0.4386) %>% #normalize values using PAAS data from Pourmand et al. 2012
    select("Sample", "La", "Ce", "Pr", "Nd", "Sm", "Eu", "Gd", "Dy", "Y", "Ho", "Er", "Tm", "Yb", "Lu") %>% #filter out non normalized values
  left_join(cement_data, by = c("Sample" = "Sample")) %>%#attach cement to each observation
  mutate(Sample_group = case_when( #add new column for grouping replicates by sample name
   str_detect(Sample, " 1 3") == TRUE ~ "FUWM 1 3",
   str_detect(Sample, " 3.5 H 1") == TRUE ~ "FUWM 3.5 H 1",
   str_detect(Sample, " 3.5 H 2") == TRUE ~ "FUWM 3.5 H 2",
   str_detect(Sample, " 8.5 2") == TRUE ~ "FUWM 8.5 2",
   str_detect(Sample, " 8.5 3") == TRUE ~ "FUWM 8.5 3",
   str_detect(Sample, " 16 T 4") == TRUE ~ "FUWM 16 T 4",
   str_detect(Sample, " 16 T 5") == TRUE ~ "FUWM 16 T 5",
   .default = NA
  )) %>%
  mutate(run = case_when(str_detect(Sample, "dil") == TRUE ~ "Diluted", .default = "Original")) #add new column to label diluted replicates and original replicates


normal <- data.frame(t(normalize[2:15]))#transpose and remove first row containing sample names and cement row
colnames(normal) <- all_rerun$Sample #rename column names with sample names
normal <- tibble::rownames_to_column(normal, "element") %>%
  mutate(element = fct_inorder(element)) %>% #order elements
  pivot_longer(-element, names_to = "Sample", values_to = "Value") %>% #pivot data to have each element value as observation
  left_join(cement_data, by = c("Sample" = "Sample")) %>% #attach cement to each observation 
  mutate(Sample_group = case_when( #add new column for grouping replicates by sample name
   str_detect(Sample, " 1 3") == TRUE ~ "FUWM 1 3",
   str_detect(Sample, " 3.5 H 1") == TRUE ~ "FUWM 3.5 H 1",
   str_detect(Sample, " 3.5 H 2") == TRUE ~ "FUWM 3.5 H 2",
   str_detect(Sample, " 8.5 2") == TRUE ~ "FUWM 8.5 2",
   str_detect(Sample, " 8.5 3") == TRUE ~ "FUWM 8.5 3",
   str_detect(Sample, " 16 T 4") == TRUE ~ "FUWM 16 T 4",
   str_detect(Sample, " 16 T 5") == TRUE ~ "FUWM 16 T 5",
   .default = NA
  )) %>%
  mutate(run = case_when(str_detect(Sample, "dil") == TRUE ~ "Diluted", .default = "Original")) #add new column to label diluted replicates and original replicates

```

## Function to remove non-diluted replicates from seq. leach data
```{r}
dil_remove <- function(data) {
  data %>%
    filter(is.na(Sample_group) | run == "Diluted") #keeps rows that are either from single leach or the diluted sequential run
}
```

## Anomalies

```{r orig anomaly calculations}
#calculate anomalies, formulas from Tostevin et al. 2016
orig_anomaly <- orig_normalize %>%
  mutate(
    Ce_anomaly = Ce/(Pr^2/Nd),
    Y_Ho_ratio = orig_data$Y/orig_data$Ho,
    Eu_anomaly = (2*Eu)/(Sm  + Gd),
    BSI = (2*(Sm + Gd + Dy)/3)/((La +Pr + Nd)/3+(Ho + Er +Tm +Yb +Lu)/5))

#generate summary statistics
orig_anomaly_summ <- orig_anomaly %>%
  group_by(Cement) %>%
  summarise(
    Ce_mean = mean(Ce_anomaly),
    Ce_sd = sd(Ce_anomaly),
    Ce_max = max(Ce_anomaly),
    Ce_min = min(Ce_anomaly),
    YH_mean = mean(Y_Ho_ratio),
    YH_sd = sd(Y_Ho_ratio),
    YH_max = max(Y_Ho_ratio),
    YH_min = min(Y_Ho_ratio),
    Eu_mean = mean(Eu_anomaly),
    Eu_sd = sd(Eu_anomaly),
    Eu_max = max(Eu_anomaly),
    Eu_min = min(Eu_anomaly),
    BSI_mean = mean(BSI),
    BSI_sd = sd(BSI),
    BSI_max = max(BSI),
    BSI_min = min(BSI)
  )
```

```{r rerun anomaly calculations}
#calculate anomalies, formulas from Tostevin et al. 2016
anomaly <- normalize %>%
  mutate(
    Ce_anomaly = Ce/(Pr^2/Nd),
    Y_Ho_ratio = all_rerun$Y/all_rerun$Ho,
    Eu_anomaly = (2*Eu)/(Sm  + Gd),
    BSI = (2*(Sm + Gd + Dy)/3)/((La +Pr + Nd)/3+(Ho + Er +Tm +Yb +Lu)/5)) 

#generate summary statistics
anomaly_summ <- anomaly %>%
  group_by(Cement) %>%
  summarise(
    Ce_mean = mean(Ce_anomaly),
    Ce_sd = sd(Ce_anomaly),
    Ce_max = max(Ce_anomaly),
    Ce_min = min(Ce_anomaly),
    YH_mean = mean(Y_Ho_ratio),
    YH_sd = sd(Y_Ho_ratio),
    YH_max = max(Y_Ho_ratio),
    YH_min = min(Y_Ho_ratio),
    Eu_mean = mean(Eu_anomaly),
    Eu_sd = sd(Eu_anomaly),
    Eu_max = max(Eu_anomaly),
    Eu_min = min(Eu_anomaly),
    BSI_mean = mean(BSI),
    BSI_sd = sd(BSI),
    BSI_max = max(BSI),
    BSI_min = min(BSI)
  )
```

#Calculate averages

```{r orig elemental conc. averages per cement}
orig_cement_avg <- orig_normal %>%
  group_by(Cement, element) %>%
  summarise(
    n = n(),
    avg = mean(Value, na.rm = TRUE),
    sd = sd(Value)
  )
orig_cement_avg$Cement <- factor(orig_cement_avg$Cement, levels = c("Spar", "Microspar", "Manganese", "Micrite", "Micrite (SSF)", "Micrite (spicule)", "Microbial", "Microbial (SSF)", "Laminar Microbial", "Laminar Microbial (Strom)", "Laminar Microbial (sponge)", "Laminar Calcrete"))
```

```{r rerun elemental conc. averages per cement}
cement_avg <- normal %>%
  group_by(Cement, element) %>%
  summarise(
    n = n(),
    avg = mean(Value, na.rm = TRUE),
    sd = sd(Value)
  )
cement_avg$Cement <- factor(cement_avg$Cement, levels = c("Spar", "Microspar", "Manganese", "Micrite", "Micrite (SSF)", "Micrite (spicule)", "Microbial", "Microbial (SSF)", "Laminar Microbial", "Laminar Microbial (Strom)", "Laminar Microbial (sponge)", "Laminar Calcrete", "Micrite Above", "Micrite Below"))
```

## Combine datasets

```{r combine element averages from both methods}
combo_data <- cement_avg %>%
  mutate(method = "Sequential leach") #%>%
#  mutate_at(2:31, as.numeric)
combo_data <- orig_cement_avg %>%
  mutate(method = "Single leach") %>%
  #mutate_at(2:31, as.numeric) %>%
  bind_rows(combo_data) %>%
  mutate(method = factor(method, levels = c("Single leach", "Sequential leach")))
```


```{r combine anomaly data from both methods}
combo_anomaly <- anomaly %>%
  mutate(method = "Sequential leach")
combo_anomaly <- orig_anomaly %>%
  mutate(method = "Single leach") %>%
  bind_rows(combo_anomaly) %>%
  mutate(method = factor(method, levels = c("Single leach", "Sequential leach")))
```

## Plots
``` {r orig data spider}
cement_aio <- orig_cement_avg %>% filter(element != "Lu") #filter out Lu due to conc. lower than detection limit
cement_aio <- ggplot(cement_aio, aes(x = element, y = avg, color = Cement)) + 
  geom_point() +
  geom_line(aes(group = Cement), size = 1) +
  scale_y_log10() +
  scale_color_brewer(palette = "Set1") +
  theme(
   panel.background = element_rect(fill = "#C3C3C3"),
    legend.key = element_rect(fill = "#C3C3C3")
    ) +
  xlab("Element") +
  ylab("Shale (PAAS) normalized concentration")
cement_aio
```

``` {r rerun data spider}
cement_aio <- ggplot(cement_avg, aes(x = element, y = avg, color = Cement)) + 
  geom_point() +
  geom_line(aes(group = Cement), size = 1) +
  scale_y_log10() +
  scale_color_brewer(palette = "Set1") +
  theme(
   panel.background = element_rect(fill = "#C3C3C3"),
    legend.key = element_rect(fill = "#C3C3C3")
    ) +
  xlab("Element") +
  ylab("Shale (PAAS) normalized concentration")
cement_aio
```

```{r combo spider plot by run}
ggplot(combo_data, aes(x = element, y = avg, color = Cement)) +
  geom_point() +
  geom_line(aes(group = Cement), size = 1) +
  scale_y_log10() +
  facet_wrap(vars(method)) +
  scale_color_brewer(name = "Cement", palette = "Set1") +
  theme(
   panel.background = element_rect(fill = "#C3C3C3"),
    legend.key = element_rect(fill = "#C3C3C3")
    ) +
  xlab("Element") +
  ylab("Shale (PAAS) normalized concentration")
```

```{r combo spider plot by cement}
ggplot(combo_data, aes(x = element, y = avg, color = method)) +
  geom_point() +
  geom_line(aes(group = method), size = 1) +
  scale_y_log10() +
  facet_wrap(vars(Cement)) +
  scale_color_brewer(name = "Method", palette = "Set2") +
  xlab("Element") +
  ylab("Shale (PAAS) normalized concentration")
```

```{r ce anomalies}
ggplot(data = combo_anomaly, aes(x = Cement, y = Ce_anomaly, fill = method, color = method)) +
  annotate("rect", xmin= -Inf, xmax= Inf, ymin= 1.2 , ymax= Inf, alpha=0.2, fill="red") +
  annotate("rect", xmin = -Inf, xmax = Inf, ymin = -Inf, ymax = 0.8, alpha = 0.2, fill = "blue") +
  geom_boxplot() +
  scale_color_manual(name = "Method", values = c("darkgreen", "darkorange3")) +
  scale_fill_brewer(name = "Method", palette = "Set2") +
  geom_hline(yintercept = 0.8, color = "blue") +
  geom_hline(yintercept = 1.2, color = "red") +
  xlab("Texture") +
  ylab("Ce Anomaly")
  
```

```{r Y/Ho ratios}
ggplot(data = combo_anomaly, aes(x = Cement, y = Y_Ho_ratio, fill = method, color = method)) +
  annotate("rect", xmin = -Inf, xmax = Inf, ymin = 36, ymax = Inf, alpha = 0.2, fill = "blue") +
  geom_boxplot() +
  scale_color_manual(name = "Method", values = c("darkgreen", "darkorange3")) +
  scale_fill_brewer(name = "Method", palette = "Set2") +
  geom_hline(yintercept = 36, color = "blue") +
  xlab("Texture") +
  ylab("Y/Ho Ratio")
  
```

```{r Y/Ho over Ce/Ce*}
dil_remove(combo_anomaly) %>%
ggplot(aes(x = Ce_anomaly, y = Y_Ho_ratio, color = Cement)) +
  geom_point() +
  facet_wrap(vars(method)) +
  theme(
   panel.background = element_rect(fill = "#C3C3C3"),
    legend.key = element_rect(fill = "#C3C3C3")
    ) +
  scale_color_brewer(palette = "Set1") +
  xlab("Ce/Ce*") +
  ylab("Y/Ho Ratio")

```

```{r comparing rerun replicates spiders}
normal %>%
  drop_na(Sample_group) %>%
ggplot(aes(x = element, y = Value, color = run)) +
  geom_point() +
  geom_line(aes(group = Sample)) +
  facet_wrap(vars(Sample_group)) +
  scale_color_brewer(palette = "Set1")+
  theme(
   panel.background = element_rect(fill = "#C3C3C3"),
    legend.key = element_rect(fill = "#C3C3C3")
    )
```

## Statistical Analysis
```{r Ce methods ANOVA}
ce_aov <- aov(data = combo_anomaly, Ce_anomaly ~ method)
summary(ce_aov)
```

```{r Ce cements ANOVA and Tukey HSD}
ce_aov <- aov(data = combo_anomaly, Ce_anomaly ~ Cement) #ANOVA
summary(ce_aov)

tukey <- TukeyHSD(ce_aov)
tukey_results <- as.data.frame(tukey[1]) %>%
  select(Cement.p.adj)
```